const traducao = {
    "winning pattern array": "matriz de padrao vencedor",
    "player 'X' plays first": "jogador 'X' joga primeiro",
    "disable all buttons": "desativar todos os botões",
    "enable popup": "ativar pop-up",
    "enable all buttons (for new games and restart)": "ativar todos os botões (para novos jogos e reiniciar)",
    "disable popup": "desativar pop-up",
    "this function is executed when a player wins": "esta função é executada quando um jogador ganha",
    "letter": "carta",
    "win": "ganhar",
    "wins": "vitórias",
    "checker": "verificador",
    "loop through all win patterns": "percorrer todos os padrões de vitória",
    "check if elements are filled ": "verifique se os elementos estão preenchidos",
    "if all 3 buttons have same values then pass the value to winFunction": "se todos os 3 botões tiverem os mesmos valores, passe o valor para winFunction",
    "Display X/0 on click": "Exibir X/0 ao clicar",
    "increment count on each click": "contagem de incremento em cada clique",
    "Enable Buttons and disable popup on page load": "Ativar botões e desativar pop-up no carregamento da página",    
}